version: '3.1'
services:
  traffic_postgres:
    image: postgres
    container_name: traffic_postgres
    environment:
      POSTGRES_DB: traffic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - traffic
  traffic_light_back:
    build:
      context: .
    container_name: traffic_light_back
    ports:
      - 8080:8080
    environment:
      DB_URL: jdbc:postgresql://traffic_postgres:5432/traffic
    depends_on:
      - traffic_postgres
    networks:
      - traffic

networks:
  traffic:
    driver: bridge